/* Entry 10 — The winter plan. A `plan`: Bertrand writes the winter month by month (ice in
   December at the Crèmerie and Cogne; ski descents in January once the Aiguille du Midi
   lift reopens; longer ski routes and serious gullies in February; a multi-day raid in
   March; the probatoire in spring), three rules, the practical side (shop from 5 Dec,
   studio paid to March), the Canada question left open, and Addie once, earned by the word
   "mars" on the sheet. B2. Grammar: futur simple as the mood of a plan; futur antérieur;
   si + présent → futur vs conditionnel; en attendant que + subjonctif; dès que / quand +
   futur; pronoun order (le lui). Escaping: CLAUDE.md §8. */
FelixNotes.register({
  id:'le-plan', no:10, date:'2026-11-09', kind:'plan', level:'B2',
  title:'Le plan pour l\'hiver', titleEn:'The plan for the winter',
  place:'Les Praz de Chamonix', lat:45.9400, lng:6.8850,
  fr:[
    "Cuisine de Bertrand, deuxième fois. Cette fois, il a sorti une feuille et il a écrit lui-même, mois par mois, de son écriture serrée. Décembre : la glace. La Crèmerie, au-dessus d'Argentière, dès qu'elle se forme, et Cogne, de l'autre côté du tunnel, où les cascades tiennent tout l'hiver. Janvier : le ski, les descentes qui manquent à ma liste, autour de la Vallée Blanche, quand la benne de l'Aiguille du Midi rouvrira. Février : de plus longues courses de ski, du côté d'Argentière, à peau de phoque depuis le bas, puisque le téléphérique du sommet des Grands Montets ne tourne plus depuis l'incendie de 2018, et une ou deux goulottes sérieuses. Mars : un raid de plusieurs jours, Chamonix–Zermatt, s'il y a de la neige et un partenaire. Puis le printemps, et le probatoire.",
    "Il a posé trois règles, sans lever le stylo. Je ne partirai jamais seul en glace. Je noterai tout après chaque course : les conditions, l'horaire, le matériel, ce qui a marché et ce qui n'a pas marché. Et je ne compterai pas les courses, je compterai les jours dehors. « Quand tu auras fait tout ça, on reparlera. Si tu ne l'as pas fait, on reparlera aussi, mais pas de la même chose. »",
    "Côté pratique : le magasin commence le 5 décembre, les week-ends et les vacances scolaires. Le studio est payé jusqu'à mars. Ce n'est pas confortable, mais c'est clair, et j'aime ce qui est clair.",
    "Et après ? Après, je ne sais pas. Peut-être le Canada, un jour, pour continuer là-bas ce que je commence ici. Eric dirait oui tout de suite. Il ne le dira pas, parce que je ne le lui demanderai pas cette année. L'année prochaine ? Dans cinq ans ? Jamais ? Je n'ai pas de réponse, et pour une fois, ça ne me dérange pas.",
    "En recopiant la feuille, je me suis arrêté sur « mars ». Mars, c'est le mois où elle venait à Revelstoke, chaque année. Si je ne suis pas là-bas en mars, je ne saurai pas si elle est revenue. Je ne le saurais pas de toute façon : je n'ai jamais eu son numéro. J'ai écrit « mars » sur ma feuille, et je suis passé à avril.",
    "La Crèmerie n'est pas encore formée. Alors, en attendant que la glace veuille bien : course à pied le matin, la salle le soir, et la feuille sur le mur, au-dessus de la table, là où je la verrai tous les jours."
  ],
  en:[
    "Bertrand's kitchen, second time. This time he took out a sheet of paper and wrote it himself, month by month, in his cramped handwriting. December: ice. The Crèmerie, above Argentière, as soon as it forms, and Cogne, on the other side of the tunnel, where the icefalls hold all winter. January: skiing, the descents missing from my list, around the Vallée Blanche, once the Aiguille du Midi cable car reopens. February: longer ski routes, on the Argentière side, on skins from the bottom, since the top cable car of the Grands Montets hasn't run since the 2018 fire, and one or two serious gullies. March: a multi-day tour, Chamonix–Zermatt, if there's snow and a partner. Then spring, and the exam.",
    "He set three rules, without lifting the pen. I will never go out on ice alone. I will write everything down after each route: conditions, timings, gear, what worked and what didn't. And I won't count routes, I'll count days outside. \"When you've done all that, we'll talk again. If you haven't done it, we'll talk again too, but not about the same thing.\"",
    "Practical side: the shop starts on 5 December, weekends and school holidays. The studio is paid until March. It isn't comfortable, but it's clear, and I like what is clear.",
    "And after? After, I don't know. Maybe Canada, one day, to continue over there what I'm starting here. Eric would say yes straight away. He won't say it, because I won't ask him this year. Next year? In five years? Never? I have no answer, and for once, that doesn't bother me.",
    "Copying out the sheet, I stopped on \"March.\" March is the month she used to come to Revelstoke, every year. If I'm not there in March, I won't know whether she came back. I wouldn't know anyway: I never had her number. I wrote \"March\" on my sheet, and moved on to April.",
    "The Crèmerie hasn't formed yet. So, while waiting for the ice to be willing: running in the morning, the climbing gym in the evening, and the sheet on the wall, above the table, where I'll see it every day."
  ],
  simple:[
    [ // ¶ 0
      {fr:"Je suis chez Bertrand, dans sa cuisine. C'est la deuxième fois.", en:"I am at Bertrand's place, in his kitchen. It is the second time."},
      {fr:"Cette fois, il a pris une feuille de papier. Il a écrit le plan, mois par mois. Son écriture est petite.", en:"This time, he took a sheet of paper. He wrote the plan, month by month. His handwriting is small."},
      {fr:"En décembre : la glace.", en:"In December: ice."},
      {fr:"Je vais grimper à la Crèmerie, près d'Argentière, quand la glace arrive. Et aussi à Cogne, de l'autre côté du tunnel. Là-bas, les cascades de glace restent tout l'hiver.", en:"I am going to climb at the Crèmerie, near Argentière, when the ice comes. And also at Cogne, on the other side of the tunnel. There, the ice waterfalls stay all winter."},
      {fr:"En janvier : le ski. Il me manque des descentes pour ma liste. Je vais les faire autour de la Vallée Blanche, quand le téléphérique de l'Aiguille du Midi va rouvrir.", en:"In January: skiing. I am missing some descents for my list. I am going to do them around the Vallée Blanche, when the Aiguille du Midi cable car reopens."},
      {fr:"En février : des sorties de ski plus longues, du côté d'Argentière. On montera avec les peaux, parce que le téléphérique du haut des Grands Montets a brûlé en 2018 et ne marche plus. Et un ou deux couloirs de glace difficiles.", en:"In February: longer ski trips, on the Argentière side. We'll go up on skins, because the top cable car of the Grands Montets burned in 2018 and doesn't run any more. And one or two hard ice gullies."},
      {fr:"En mars : un grand voyage à ski de plusieurs jours, de Chamonix à Zermatt. Mais seulement s'il y a de la neige et un partenaire.", en:"In March: a big multi-day ski trip, from Chamonix to Zermatt. But only if there is snow and a partner."},
      {fr:"Après, c'est le printemps, et l'examen.", en:"After that, it is spring, and the exam."}
    ],
    [ // ¶ 1
      {fr:"Il a donné trois règles. Il n'a pas levé le stylo.", en:"He gave three rules. He did not lift his pen."},
      {fr:"Un : je ne vais jamais grimper la glace seul.", en:"One: I am never going to climb ice alone."},
      {fr:"Deux : après chaque sortie, je vais tout écrire. Les conditions, l'heure, le matériel. Ce qui a bien marché et ce qui n'a pas marché.", en:"Two: after each outing, I am going to write everything down. The conditions, the time, the gear. What went well and what did not work."},
      {fr:"Trois : je ne vais pas compter les sorties. Je vais compter les jours dehors.", en:"Three: I am not going to count the outings. I am going to count the days outside."},
      {fr:"« Quand tu auras fait tout ça, on va reparler. »", en:"“When you have done all that, we will talk again.”"},
      {fr:"« Si tu ne l'as pas fait, on va parler aussi. Mais pas de la même chose. »", en:"“If you have not done it, we will talk too. But not about the same thing.”"}
    ],
    [ // ¶ 2
      {fr:"Pour l'argent : je commence à travailler au magasin le 5 décembre. Je travaille les week-ends et les vacances scolaires.", en:"For money: I start working at the shop on 5 December. I work weekends and school holidays."},
      {fr:"J'ai payé mon studio jusqu'en mars.", en:"I have paid for my studio until March."},
      {fr:"Ce n'est pas facile, mais c'est clair. Et j'aime ce qui est clair.", en:"It is not easy, but it is clear. And I like what is clear."}
    ],
    [ // ¶ 3
      {fr:"Et après ?", en:"And after?"},
      {fr:"Après, je ne sais pas.", en:"After, I don't know."},
      {fr:"Peut-être le Canada, un jour. Je veux continuer là-bas ce que je commence ici.", en:"Maybe Canada, one day. I want to continue over there what I am starting here."},
      {fr:"Eric dirait oui tout de suite.", en:"Eric would say yes right away."},
      {fr:"Mais il ne va rien dire. Parce que cette année, je ne vais pas lui demander.", en:"But he will not say anything. Because this year, I am not going to ask him."},
      {fr:"L'année prochaine ?", en:"Next year?"},
      {fr:"Dans cinq ans ?", en:"In five years?"},
      {fr:"Jamais ?", en:"Never?"},
      {fr:"Je n'ai pas de réponse. Et pour une fois, ça ne me dérange pas.", en:"I have no answer. And for once, it does not bother me."}
    ],
    [ // ¶ 4
      {fr:"J'ai recopié la feuille. Je me suis arrêté sur le mot « mars ».", en:"I copied out the sheet. I stopped on the word “March.”"},
      {fr:"Mars, c'est le mois où elle venait à Revelstoke, chaque année.", en:"March is the month when she came to Revelstoke, every year."},
      {fr:"Si je ne suis pas là-bas en mars, je ne saurai pas si elle est revenue.", en:"If I am not there in March, I will not know if she came back."},
      {fr:"De toute façon, je ne le saurais pas : je n'ai jamais eu son numéro.", en:"Anyway, I would not know: I never had her number."},
      {fr:"J'ai écrit « mars » sur ma feuille. Puis je suis passé à avril.", en:"I wrote “March” on my sheet. Then I moved on to April."}
    ],
    [ // ¶ 5
      {fr:"La glace de la Crèmerie n'est pas encore là.", en:"The ice at the Crèmerie is not there yet."},
      {fr:"Alors j'attends la glace. En attendant, je cours le matin et je vais à la salle d'escalade le soir. La feuille est sur le mur, au-dessus de la table. Je la verrai tous les jours.", en:"So I wait for the ice. While I wait, I run in the morning and I go to the climbing gym in the evening. The sheet is on the wall, above the table. I will see it every day."}
    ]
  ],
  read:[
    [ // ¶ 0
      [ {t:"Cuisine", k:"son", n:"ui is one glide /ɥi/, single s = z: “kwi-zin” /kɥi.zin/."},
        {t:"Bertrand", k:"muet", n:"Final d silent: “bèr-tran” /bɛʁ.tʁɑ̃/."},
        {t:"deuxième", k:"son", n:"The x is said as z: “deu-zyèm” /dø.zjɛm/."} ],
      [ {t:"feuille", k:"son", n:"euil = /œj/, one syllable: “feuy” /fœj/."},
        {t:"et il a écrit", k:"liaison", n:"No liaison after et: “é i-la é-kri”. The t of écrit is silent."},
        {t:"lui-même", k:"son", n:"ui glide again: “lwi-mèm” /lɥi.mɛm/."},
        {t:"mois par mois", k:"muet", n:"The s of mois is silent: “mwa par mwa”."},
        {t:"son écriture", k:"liaison", n:"Required liaison: “son-né-kri-tur” /sɔ̃.n‿e.kʁi.tyʁ/."},
        {t:"serrée", k:"son", n:"rr is one r; ée = /e/: “sè-ré” /se.ʁe/."} ],
      [ {t:"Décembre", k:"son", n:"em = nasal /ɑ̃/: “dé-sanbr” /de.sɑ̃bʁ/."} ],
      [ {t:"Crèmerie", k:"mot", n:"The middle e drops: “krèm-ri” /kʁɛm.ʁi/."},
        {t:"au-dessus", k:"son", n:"dessus = /y/ (“above”), not dessous /u/ (“below”): “o-d'su” /od.sy/."},
        {t:"d'Argentière", k:"mot", n:"“dar-jan-tyèr” /daʁ.ʒɑ̃.tjɛʁ/. ge = “zh”, en = nasal."},
        {t:"dès qu'elle", k:"muet", n:"The s of dès is silent: “dè kèl”."},
        {t:"Cogne", k:"mot", n:"gn = “ny” as in canyon: “kony” /kɔɲ/, one syllable."},
        {t:"tunnel", k:"son", n:"u = /y/: “tu-nèl” /ty.nɛl/, not the English “tun-nel”."},
        {t:"tiennent", k:"muet", n:"-ent of the verb is silent: “tyèn” /tjɛn/, one syllable."},
        {t:"tout l'hiver", k:"muet", n:"The t of tout is silent; hiver has a mute h, hence the elision l': “tou li-vèr”."} ],
      [ {t:"Janvier", k:"muet", n:"The r of -ier is silent: “jan-vyé” /ʒɑ̃.vje/."},
        {t:"manquent à", k:"liaison", n:"Optional liaison (“mank-ta”), normal in reading aloud, usually skipped in speech. -ent itself is silent: “mank a”."},
        {t:"benne", k:"mot", n:"The cable-car cabin: “bèn” /bɛn/."},
        {t:"l'Aiguille", k:"mot", n:"Here the u IS said: “lè-gwiy” /le.gɥij/. The ill = “y”."},
        {t:"rouvrira", k:"son", n:"Futur of rouvrir: “rou-vri-ra” /ʁu.vʁi.ʁa/ — two r's close together; keep them light."} ],
      [ {t:"Février", k:"son", n:"Three syllables: “fé-vri-yé” /fe.vʁi.je/. The r of -ier is silent."},
        {t:"plus longues", k:"muet", n:"The s of plus is silent before a consonant; gu = hard g: “plu long” /ply lɔ̃ɡ/."},
        {t:"et une ou deux", k:"liaison", n:"No liaison after et; then une slides onto ou: “é u-nou deu”."},
        {t:"goulottes", k:"mot", n:"A narrow ice or mixed gully: “gou-lot” /ɡu.lɔt/. Final s silent."},
        {t:"sérieuses", k:"son", n:"-euses = “euz” /øz/: “sé-ryeuz” /se.ʁjøz/."}, {t:"à peau de phoque", k:"son", n:"eau = “o”; ph = f: “a po d' fok” /a po d fɔk/."}, {t:"puisque le téléphérique", k:"son", n:"puisque = “puis-k'”, the s is said; téléphérique = “té-lé-fé-rik”."}, {t:"depuis l'incendie", k:"son", n:"Two different nasals: in = /ɛ̃/, en = /ɑ̃/: “lin-san-di” /lɛ̃.sɑ̃.di/."}, {t:"2018", k:"mot", say:"deux mille dix-huit", n:"deux mille dix-huit: the x of dix links as z, “di-zuit”."} ],
      [ {t:"Mars", k:"son", n:"The s of mars IS pronounced: “mars” /maʁs/."},
        {t:"raid", k:"mot", n:"A multi-day ski traverse. The d is said: “rèd” /ʁɛd/."},
        {t:"plusieurs jours", k:"muet", n:"The s of plusieurs is silent before a consonant: “plu-zyeur jour”."},
        {t:"Chamonix–Zermatt", k:"mot", n:"x of Chamonix silent: “sha-mo-ni”. Zermatt: “zèr-mat” /zɛʁ.mat/."},
        {t:"s'il y a", k:"son", n:"Careful: “si-li-a”; in speech often just “sil-ya”."},
        {t:"et un", k:"liaison", n:"No liaison after et: “é un”."} ],
      [ {t:"Puis", k:"muet", n:"s silent: “pwi” /pɥi/."},
        {t:"printemps", k:"muet", n:"p and s both silent: “prin-tan” /pʁɛ̃.tɑ̃/."},
        {t:"probatoire", k:"mot", n:"“pro-ba-twar” /pʁɔ.ba.twaʁ/. oi = “wa”."} ]
    ],
    [ // ¶ 1
      [ {t:"trois règles", k:"liaison", n:"No liaison before a consonant: “trwa règl”. règles is one syllable."},
        {t:"sans lever", k:"son", n:"s of sans silent; the e of lever often drops: “san l'vé”."},
        {t:"stylo", k:"son", n:"y = /i/: “sti-lo” /sti.lo/."} ],
      [ {t:"partirai", k:"son", n:"Futur -rai ends in /e/: “par-ti-ré” /paʁ.ti.ʁe/."},
        {t:"seul en", k:"enchainement", n:"The l slides onto en: “seu-lan” /sœ.l‿ɑ̃/."} ],
      [ {t:"noterai", k:"son", n:"The middle e drops: “not-ré” /nɔt.ʁe/."},
        {t:"après", k:"muet", n:"The s is silent: “a-prè” /a.pʁɛ/."},
        {t:"conditions", k:"son", n:"Here -tion = “syon” (no s before it): “kon-di-syon” /kɔ̃.di.sjɔ̃/. Compare questions, “kès-tyon”."},
        {t:"l'horaire", k:"mot", n:"Mute h, so l' elides: “lo-rèr” /lɔ.ʁɛʁ/."},
        {t:"matériel", k:"son", n:"“ma-té-ryèl” /ma.te.ʁjɛl/, the l is said."},
        {t:"ce qui n'a pas", k:"son", n:"Listen for the n: ce qui a (“s' ki a”) vs ce qui n'a (“s' ki na”). One consonant flips the meaning."} ],
      [ {t:"compterai", k:"muet", n:"The p is silent, the middle e drops: “kon-t'ré” /kɔ̃t.ʁe/."},
        {t:"dehors", k:"muet", n:"Two syllables, final s silent: “deu-or” /də.ɔʁ/."} ],
      [ {t:"Quand tu", k:"muet", n:"The d of quand is silent before a consonant: “kan tu”."},
        {t:"tu auras", k:"son", n:"Written tu auras; in speech often squeezed to “t'o-ra”. s silent."},
        {t:"fait tout", k:"muet", n:"Both t's silent: “fè tou”."},
        {t:"reparlera", k:"son", n:"Little e's drop: “r'par-l'ra” /ʁə.paʁl.ʁa/."} ],
      [ {t:"l'as pas", k:"muet", n:"The s of as and pas are both silent: “la pa”."},
        {t:"mais pas", k:"muet", n:"s silent: “mè pa”."} ]
    ],
    [ // ¶ 2
      [ {t:"magasin", k:"son", n:"Single s between vowels = z: “ma-ga-zin” /ma.ɡa.zɛ̃/."},
        {t:"5 décembre", say:"cinq décembre", k:"mot", n:"Read “cinq décembre”. In dates the q of cinq is normally said: “sink dé-sanbr” /sɛ̃k de.sɑ̃bʁ/."},
        {t:"week-ends", k:"mot", n:"A loanword, French-style: “wi-kènd” /wi.kɛnd/. The d is said, the s is not."},
        {t:"vacances scolaires", k:"muet", n:"Final s's silent: “va-kans sko-lèr”."} ],
      [ {t:"payé", k:"son", n:"ay = “è-y”: “pè-yé” /pe.je/."},
        {t:"mars", k:"son", n:"s pronounced: “mars”."} ],
      [ {t:"n'est pas", k:"muet", n:"“nè pa”: both final consonants silent."},
        {t:"confortable", k:"son", n:"on = nasal /ɔ̃/: “kon-for-tabl” /kɔ̃.fɔʁ.tabl/."},
        {t:"qui est clair", k:"son", n:"No link between qui and est: “ki è klèr”. The r of clair is said."} ]
    ],
    [ // ¶ 3
      [ {t:"Et après", k:"liaison", n:"No liaison after et: “é a-prè”."} ],
      [ {t:"je ne sais pas", k:"son", n:"Read aloud “jeun' sè pa”; fast speech shrinks it to “ché pa”."} ],
      [ {t:"Peut-être", k:"enchainement", n:"The t links: “peu-tètr” /pø.tɛtʁ/. In casual speech often just “p'tèt”."},
        {t:"continuer", k:"son", n:"“kon-ti-nu-é” /kɔ̃.ti.ny.e/; in speech the u often glides into é."},
        {t:"là-bas", k:"muet", n:"s silent: “la-ba”."},
        {t:"commence ici", k:"enchainement", n:"The s sound of commence slides onto ici: “ko-man-si-si”."} ],
      [ {t:"Eric", k:"mot", n:"French-style: “é-rik” /e.ʁik/."},
        {t:"dirait oui", k:"liaison", n:"No liaison before oui — it blocks linking like an aspirated h: “di-rè | wi”."},
        {t:"tout de suite", k:"son", n:"Usually run together: “tout-suit” /tut.sɥit/."} ],
      [ {t:"je ne le lui", k:"son", n:"A chain of small words; spoken, the e's fall: roughly “jeun' l'lwi”."},
        {t:"demanderai", k:"son", n:"“d'man-d'ré” /də.mɑ̃d.ʁe/: futur -rai = /e/."},
        {t:"cette année", k:"enchainement", n:"The t slides onto année: “sè-ta-né” /sɛ.t‿a.ne/."} ],
      [ {t:"L'année", k:"son", n:"Not nasal: nn goes with the next syllable, “la-né” /la.ne/."} ],
      [ {t:"cinq ans", k:"enchainement", n:"The q = k slides onto ans: “sin-kan” /sɛ̃.k‿ɑ̃/."} ],
      [],
      [ {t:"pour une fois", k:"enchainement", n:"The r of pour slides onto une: “pou-run fwa”."},
        {t:"dérange", k:"son", n:"an = nasal, ge = “zh”: “dé-ranj” /de.ʁɑ̃ʒ/."} ]
    ],
    [ // ¶ 4
      [ {t:"En recopiant", k:"son", n:"No liaison (r follows). The e drops: “an r'ko-pyan” /ɑ̃ ʁə.kɔ.pjɑ̃/."},
        {t:"suis arrêté", k:"liaison", n:"Optional liaison, common when reading: “swi-za-rè-té”."},
        {t:"mars", k:"son", n:"s pronounced: “mars” /maʁs/."} ],
      [ {t:"mois où elle", k:"muet", n:"The s of mois stays silent, no liaison: “mwa ou èl”."},
        {t:"venait à", k:"liaison", n:"Optional liaison (“v'nè-ta”), rare in speech; usually “v'nè a”."},
        {t:"chaque année", k:"enchainement", n:"The k sound slides onto année: “sha-ka-né”."} ],
      [ {t:"là-bas en mars", k:"muet", n:"No liaison after là-bas: “la-ba | an mars”."},
        {t:"saurai", k:"son", n:"Futur of savoir: “so-ré” /sɔ.ʁe/. Compare saurais in the next sentence."},
        {t:"si elle", k:"son", n:"si only elides before il/ils; here both vowels stay: “si èl”."},
        {t:"revenue", k:"son", n:"“r'v'nu” in speech; u = /y/."} ],
      [ {t:"saurais", k:"son", n:"Conditionnel: /sɔ.ʁɛ/, a slightly more open vowel than saurai /sɔ.ʁe/. Many speakers say both the same; context carries it."},
        {t:"toute façon", k:"son", n:"ç = s: “tout fa-son” /tut fa.sɔ̃/."},
        {t:"jamais eu", k:"son", n:"eu (past participle of avoir) is said /y/, like “u”: “ja-mè u”. Liaison (“ja-mè-zu”) is optional."},
        {t:"numéro", k:"son", n:"u = /y/: “nu-mé-ro” /ny.me.ʁo/."} ],
      [ {t:"J'ai écrit", k:"son", n:"“jé é-kri”: two é sounds in a row, t of écrit silent."},
        {t:"passé à avril", k:"son", n:"Three a/é vowels meet with no link: “pa-sé a a-vril”. The l of avril is said."} ]
    ],
    [ // ¶ 5
      [ {t:"Crèmerie", k:"mot", n:"“krèm-ri”."},
        {t:"pas encore", k:"liaison", n:"Optional liaison: careful “pa-zan-kor”, everyday “pa an-kor”."} ],
      [ {t:"en attendant", k:"liaison", n:"Required liaison after en: “an-na-tan-dan” /ɑ̃.n‿a.tɑ̃.dɑ̃/."},
        {t:"veuille", k:"son", n:"Subjunctive of vouloir, one syllable: “veuy” /vœj/. Rhymes with feuille."},
        {t:"course à pied", k:"enchainement", n:"The s sound slides onto à: “kour-sa pyé”. The d of pied is silent."},
        {t:"au-dessus", k:"son", n:"u = /y/: “o-d'su”."},
        {t:"là où", k:"son", n:"Two vowels, no link: “la ou”."},
        {t:"verrai", k:"son", n:"Futur of voir: “vè-ré” /ve.ʁe/, rr = one r."},
        {t:"tous les jours", k:"muet", n:"Before a noun, tous has a silent s: “tou lé jour”. (As a pronoun, tous /tus/ says it.)"} ]
    ]
  ],
  vocab:[
    ['un téléphérique','a cable car'],
    ['un incendie','a fire (a building or installation burning)'],
    ['puisque','since, given that'],
    ['une feuille','a sheet of paper; a leaf'],
    ['une écriture serrée','cramped, tight handwriting'],
    ['une cascade (de glace)','an icefall, a frozen waterfall'],
    ['dès que','as soon as'],
    ['la benne','the cable car (colloquial; le téléphérique)'],
    ['un raid','a multi-day ski tour'],
    ['un partenaire / une partenaire','a (climbing or ski) partner'],
    ['une règle','a rule'],
    ['un stylo','a pen'],
    ['l\'horaire','the timings, the schedule'],
    ['le matériel','the gear, the equipment'],
    ['les vacances scolaires','the school holidays'],
    ['confortable','comfortable'],
    ['ça ne me dérange pas','that doesn\'t bother me'],
    ['de toute façon','anyway, in any case'],
    ['passer à','to move on to'],
    ['en attendant que','while waiting for (+ subjonctif)'],
    ['la salle (d\'escalade)','the climbing gym'],
    ['noter','to write down, to note', FelixNotes.verb('noter',
      ["je note","tu notes","il/elle note","nous notons","vous notez","ils/elles notent"],
      ["j'ai noté","tu as noté","il/elle a noté","nous avons noté","vous avez noté","ils/elles ont noté"],
      ["je notais","tu notais","il/elle notait","nous notions","vous notiez","ils/elles notaient"],
      ["je noterai","tu noteras","il/elle notera","nous noterons","vous noterez","ils/elles noteront"])],
    ['rouvrir','to reopen', FelixNotes.verb('rouvrir',
      ["je rouvre","tu rouvres","il/elle rouvre","nous rouvrons","vous rouvrez","ils/elles rouvrent"],
      ["j'ai rouvert","tu as rouvert","il/elle a rouvert","nous avons rouvert","vous avez rouvert","ils/elles ont rouvert"],
      ["je rouvrais","tu rouvrais","il/elle rouvrait","nous rouvrions","vous rouvriez","ils/elles rouvraient"],
      ["je rouvrirai","tu rouvriras","il/elle rouvrira","nous rouvrirons","vous rouvrirez","ils/elles rouvriront"])],
    ['recopier','to copy out', FelixNotes.verb('recopier',
      ["je recopie","tu recopies","il/elle recopie","nous recopions","vous recopiez","ils/elles recopient"],
      ["j'ai recopié","tu as recopié","il/elle a recopié","nous avons recopié","vous avez recopié","ils/elles ont recopié"],
      ["je recopiais","tu recopiais","il/elle recopiait","nous recopiions","vous recopiiez","ils/elles recopiaient"],
      ["je recopierai","tu recopieras","il/elle recopiera","nous recopierons","vous recopierez","ils/elles recopieront"])],
    ['vouloir (bien)','to want (to be willing)', FelixNotes.verb('vouloir',
      ["je veux","tu veux","il/elle veut","nous voulons","vous voulez","ils/elles veulent"],
      ["j'ai voulu","tu as voulu","il/elle a voulu","nous avons voulu","vous avez voulu","ils/elles ont voulu"],
      ["je voulais","tu voulais","il/elle voulait","nous voulions","vous vouliez","ils/elles voulaient"],
      ["je voudrai","tu voudras","il/elle voudra","nous voudrons","vous voudrez","ils/elles voudront"])]
  ],
  gram:[
    {h:'The <em>futur simple</em> as the mood of a plan',
     p:'A plan is written in the future, and this entry is full of it: <span class="ex">je ne <b>partirai</b> jamais seul</span>, <span class="ex">je <b>noterai</b> tout</span>, <span class="ex">je <b>compterai</b> les jours</span>, <span class="ex">la benne <b>rouvrira</b></span>, <span class="ex">je la <b>verrai</b> tous les jours</span>. Regular stems are the infinitive (<em>noter-ai</em>, <em>partir-ai</em>); the irregular ones are worth a list: <em>saurai</em> (savoir), <em>verrai</em> (voir), <em>dirai</em> (dire), <em>faudra</em> (falloir), <em>voudrai</em> (vouloir), <em>reparlera</em> is regular.'},
    {h:'<em>Futur antérieur</em> vs <em>si</em> + passé composé',
     p:'Bertrand\'s two conditions: <span class="ex"><b>Quand</b> tu <b>auras fait</b> tout ça, on reparlera</span> (time clause <span class="arrow">→</span> futur antérieur, as in entry 6) and <span class="ex"><b>Si</b> tu ne l\'<b>as</b> pas <b>fait</b>, on reparlera aussi</span> (condition <span class="arrow">→</span> <em>si</em> + passé composé, never a future). Same idea, two grammars: <em>quand</em> looks at the order of events, <em>si</em> at whether it happened.'},
    {h:'<em>Je ne saurai pas</em> / <em>je ne le saurais pas</em> — one letter, two worlds',
     p:'<span class="ex">Si je ne suis pas là-bas en mars, je ne <b>saurai</b> pas</span> — <em>si</em> + présent, then <b>futur</b>: a real possibility. <span class="ex">Je ne le <b>saurais</b> pas de toute façon</span> — <b>conditionnel</b>: a hypothetical ("I wouldn\'t know anyway"). And <span class="ex">Eric <b>dirait</b> oui</span>: he would say yes (if asked). Listen for the difference: <em>saurai</em> [-re], <em>saurais</em> [-rè].'},
    {h:'<em>en attendant que</em> + subjonctif; <em>dès que</em> / <em>quand</em> + futur',
     p:'<span class="ex"><b>en attendant que</b> la glace <b>veuille</b> bien</span> <span class="arrow">→</span> while waiting for the ice to be willing. <em>en attendant que</em> takes the subjunctive (<em>veuille</em>, from <em>vouloir</em>). The time words that look forward take the future in French where English uses the present: <span class="ex"><b>quand</b> la benne <b>rouvrira</b></span> = when the lift reopens; <span class="ex"><b>dès qu\'</b>elle se forme</span> keeps the present here because it is a general fact, not a one-off.'},
    {h:'Two object pronouns in a row: <em>je ne le lui demanderai pas</em>',
     p:'<span class="ex">je ne <b>le lui</b> demanderai pas</span> <span class="arrow">→</span> I won\'t ask him (for) it. Order before the verb: <em>me / te / nous / vous</em> come first, then <em>le / la / les</em>, then <em>lui / leur</em>. So: <span class="ex">je te le dis</span> but <span class="ex">je le lui dis</span>. Also here: <span class="ex">ce que je commence ici</span> (what I\'m starting), <span class="ex">là où je la verrai</span> (there where I\'ll see it), and the recurring <span class="ex">de plus longues courses</span>.'}
  ]
});
